draft-ietf-doh-dns-over-https-latest.mkd
=> Capitalize SHOULD on DNS ID 0 requirement

draft-ietf-doh-dns-over-https-latest.mkd
=> clarify example media type is made up

draft-ietf-doh-dns-over-https-latest.mkd
Reverts dohwg/draft-ietf-doh-dns-over-https#25
=> Revert "distinguish confidentiality and authentication in security considerat…"

draft-ietf-doh-dns-over-https-latest.mkd
=> describe deadlock wrt ocsp and doh connection. should stapling.

draft-ietf-doh-dns-over-https-latest.mkd
=> reference whatwg fetch for cors. fix ref to it.

draft-ietf-doh-dns-over-https-latest.mkd
=> discuss revalidation rather than discouraging it

draft-ietf-doh-dns-over-https-latest.mkd
=> misc changes for cleanup

draft-ietf-doh-dns-over-https-latest.mkd
This text is rather subjective without data.  Changing it to "may" still brings the point without needing a reference to a study proving the sentence true.
=> Subjective

draft-ietf-doh-dns-over-https-latest.mkd
=> this is an interoprable MUST

draft-ietf-doh-dns-over-https-latest.mkd
=> Not necessarily b64

draft-ietf-doh-dns-over-https-latest.mkd
=> Be more explicit about clients' interaction with the HTTP freshness

draft-ietf-doh-dns-over-https-latest.mkd
=> explicitly talk about push trust

draft-ietf-doh-dns-over-https-latest.mkd
=> emphasize b64url in request example

draft-ietf-doh-dns-over-https-latest.mkd
Also remove extraneous comment about discovery in the charter
=> Add security considerations for caching

draft-ietf-doh-dns-over-https-latest.mkd
=> cut the abstract down

draft-ietf-doh-dns-over-https-latest.mkd
=> remind the reader http is stateless

draft-ietf-doh-dns-over-https-latest.mkd
=> explain that non 2xx means no dns answer

draft-ietf-doh-dns-over-https-latest.mkd
=> less terse about status code

draft-ietf-doh-dns-over-https-latest.mkd
=> Remove spaces

draft-ietf-doh-dns-over-https-latest.mkd
Conneg is a means, not an end.
=> Express the requirement, not the mechanism

draft-ietf-doh-dns-over-https-latest.mkd
This text does not read very well in its current form.  Since it is two
ideas, two sentences is best.
=> MTI for interoperability

draft-ietf-doh-dns-over-https-latest.mkd
=> Deal with 512 byte limit and truncation

draft-ietf-doh-dns-over-https-latest.mkd
=> can weaken the privacy and authenticity expected by the user

draft-ietf-doh-dns-over-https-latest.mkd
=> Notes from Stephane in the prematurely-closed PR #120

draft-ietf-doh-dns-over-https-latest.mkd
=> Changed the media type from message/dns to application/dns-message

draft-ietf-doh-dns-over-https-latest.mkd
Attempt to deal with #161. I'm not convinced that this is much better than the current text, but it might help others.
=> Clarify that the TC bit in the header isn't special

draft-ietf-doh-dns-over-https-latest.mkd
this paragraph is true.. but its a tad confusing and I don't think really describes anything germane to doh.
=> remove the security consideration about not using doh

draft-ietf-doh-dns-over-https-latest.mkd
This PR is against the privacy considerations branch (pr #200)
=> introduce some comparisons and rationale

draft-ietf-doh-dns-over-https-latest.mkd
=> add some specific text about cookies given their importance

draft-ietf-doh-dns-over-https-latest.mkd
this is a PR against #200 
these are pretty straight forward
=> editorial level feedback from ekr
